### ISSUE TITLE
vs2019 x64 win10

### ISSUE THREAD

**Issue by yangxingpping** [build2/bdep#3]
in libpkgconf-1.6.3+4\libpkgconf\config.h.in
version.in libbutl-0.13.0\libbutl\version.hxx.in
version.in libodb-sqlite-2.5.0-b.19\odb\sqlite\version-build2.hxx.in
version.in libodb-2.5.0-b.19\odb\version-build2.hxx.in
in build2-0.13.0\libbuild2\config.hxx.in
version.in libbpkg-0.13.0\libbpkg\version.hxx.in
version.in build2-0.13.0\libbuild2\version.hxx.in
C:\Users\Documents\build2\build2-toolchain-0.13\bdep-0.13.0\bdep\new-options.cxx(3617): error C2220:
C:\Users\Documents\build2\build2-toolchain-0.13\bdep-0.13.0\bdep\new-options.cxx(3617): warning C4819

**Comment by boris-kolpackov** [comment]
Just for my understanding, can you give some details on how you are building it? I don't believe any of our build scripts/instructions have the `/WX` flag (which is what causes error C2220).

**Comment by yangxingpping** [comment]
just follow guid [https://build2.org/install.xhtml](url) and run bat file.

**Comment by boris-kolpackov** [comment]
Ok, thanks for the information. Thought I still don't understand where the `/WX` flags is comping from. We don't pass it in any of our batch files. Do you perhaps have it set via the `CL` or `_CL_` environment variables? Could you run the following in the command prompt and send the result?

```
echo %CL%
echo %_CL%
```

**Comment by yangxingpping** [comment]
No, I just use the default configure
D:\>echo %CL%
%CL%

D:\>echo %_CL%
%_CL%

I notice that v0.13.0 and master file struct is different. How can I build bdep by myself(not just by use by the bat file),  or where can I find detail configure for  build.

**Comment by boris-kolpackov** [comment]
Very strange. Could you try the latest staged version where we have suppressed warning C4819:

https://build2.org/community.xhtml#stage

> I notice that v0.13.0 and master file struct is different, Does it means next version have a big change to previous versions?

There are some changes but it's not drastic. I am not sure which project you are comparing. What gets build with the scripts is the `build2-toolchain` amalgamation: https://github.com/build2/build2-toolchain

> How can I build bdep by myself(not just by use by the bat file), or where can I find detail configure for build.

You can find the manual installation instructions here: https://build2.org/build2-toolchain/doc/build2-toolchain-install.xhtml

**Comment by yangxingpping** [comment]
I tryed staged version

ld build2\libbuild2\c\libs{build2-c}
  正在创建库 build2\libbuild2\cxx\build2-cxx-stage.dll.lib 和对象 build2\libbuild2\cxx\build2-cxx-stage.dll.exp
  正在创建库 build2\libbuild2\c\build2-c-stage.dll.lib 和对象 build2\libbuild2\c\build2-c-stage.dll.exp
ld build2\build2\exe{b}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\hxx{export}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ft\hxx{exception}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ft\hxx{lang}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ft\hxx{shared_mutex}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\hxx{manifest-forward}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\hxx{process-details}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\hxx{small-vector-odb}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\hxx{uuid}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\hxx{uuid-io}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{builtin}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{char-scanner}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{curl}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{default-options}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{fdstream}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{filesystem}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{manifest-parser}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{manifest-serializer}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{openssl}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{optional}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{path-pattern}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{path}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{process}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{regex}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{semantic-version}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{sendmail}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{standard-version}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{unicode}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{url}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{utf8}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{utility}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\ixx{uuid}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory
  info: while installing libbutl\libbutl\txx{char-scanner}
  info: while installing libbutl\libbutl\libs{butl}
  info: while installing build2\build2\exe{b}
  info: while installing build2\dir{build2\}
  info: while installing dir{build2\}
error: unable to execute install: no such file or directory

**Comment by yangxingpping** [comment]
use clang version is ok on windows

**Comment by boris-kolpackov** [comment]
Yes, you can, though there are no specific instructions for that. You could also pre-download `build2-baseutils` and `build2-toolchain` and then use the install script's `--local` option to achieve pretty much the same result automatically.

Regarding the install error, just to confirm: if you run the `build2-install-msvc` batch file, you get the above error and if instead you run `build2-install-clang` in exactly the same way, then everything works, correct?

**Comment by yangxingpping** [comment]
Today I try staged version again,it's work. Yesterday may be something wrong with network. Thank you very much!

**Comment by boris-kolpackov** [comment]
For our records, could you let me know which code pages you are using? [This](https://serverfault.com/a/836221) suggest it can be obtained with the following PowerShell command:

```
Get-WinSystemLocale | Select-Object Name, DisplayName, 
                        @{ n='OEMCP'; e={ $_.TextInfo.OemCodePage } }, 
                        @{ n='ACP';   e={ $_.TextInfo.AnsiCodePage } }
```
