### ISSUE TITLE
Adding error checking in initial projects

### ISSUE THREAD

**Issue by feelamee** [build2/bdep#6]
I suggest to add error checking here [1](https://github.com/build2/bdep/blob/fec61ff1452369badcad35727aeb16ade2c1320a/bdep/new.cxx#L2490) and [2](https://github.com/build2/bdep/blob/fec61ff1452369badcad35727aeb16ade2c1320a/bdep/new.cxx#L2513)

This is trifle, but learn us to write good code.

**Comment by boris-kolpackov** [comment]
The `bdep-new`-generated C and C++ source code is meant to be a minimal example of a working "Hello, World" executable/library that can be built and run on a variety of platforms. While it tries not to do anything obviously wrong, it is not mean to be teaching how to write production code.
